/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "trrkdhymompsqcwlbqoy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRycmtkaHltb21wc3Fjd2xicW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2NTkxMTUsImV4cCI6MjA4NTIzNTExNX0.UtE2JEAItHIB56VcHAkMkSInduXxFrOJRU-2-JzEXcg"